version: '2.0'

services:
    proxy:
        image: jwilder/nginx-proxy
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"

    website:
        build: docker/php70
        image: web-site/php70
        env_file: ./.env
        volumes:
          - ./site:/var/www/html
        environment:
            VIRTUAL_HOST: web.site.docker
            DOMAIN_NAME: web.site.docker
        depends_on:
          - database

    database:
        image: mariadb:10.1
        environment:
             MYSQL_ROOT_PASSWORD: root
             MYSQL_DATABASE: symfony

    phpmyadmin:
         image: phpmyadmin/phpmyadmin
         environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: database
            VIRTUAL_HOST: phpmyadmin.website.docker
            DOMAIN_NAME: phpmyadmin.website.docker
         depends_on:
           - database