version: '2.0'

services:

  proxy:
      ports:
        - 80:80
        - 444:444
  database:
      volumes:
        -  "database:/var/lib/mysql"

  website:
      volumes:
        - ~/.ssh:/var/www/.ssh
        - ~/.composer:/var/www/.composer

volumes:
  database: